SIMULATOR:
  HABITAT_SIM_v0:
    ALLOW_SLIDING: false
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
    HEIGHT: 0.88
    RADIUS: 0.1
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0.0, 0.88, 0.0]
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0.0, 0.88, 0.0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0.0, 0.88, 0.0]
DATASET:
  TYPE: "SequentialObjectNav-v0"
  DATA_PATH: "data/datasets/sequential_objectnav/multion/3_ON/{split}/{split}.json.gz"
TASK:
  TYPE: "SequentialObjectNav-v0"
  ENABLE_OBJECT_COLLISIONS: false
  SUCCESS_DISTANCE: 1.5
  POSSIBLE_ACTIONS: ["FOUND", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ["SEQUENTIAL_OBJECTGOAL_CATEGORY_SENSOR", "GPS_SENSOR", "COMPASS_SENSOR", "SEQUENTIAL_EGO_MAP_SENSOR"]
  SEQUENTIAL_OBJECTGOAL_CATEGORY_SENSOR:
    SEQUENTIAL_MODE: "MYOPIC"
  GOAL_SENSOR_UUID: "objectgoal_category"
  MEASUREMENTS: ["DISTANCE_TO_NEXT_GOAL", "SEQUENTIAL_SUCCESS", "SEQUENTIAL_SPL", "PROGRESS", "PPL"]
  SEQUENTIAL_SUCCESS:
    SUCCESS_DISTANCE: 1.5
