SIMULATOR:
    AGENT_0:
        SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
DATASET:
    TYPE: "SequentialObjectNav-v0"
    DATA_PATH: "data/datasets/sequential_objectnav/unittest/{split}/{split}.json.gz"
TASK:
    TYPE: "SequentialObjectNav-v0"
    SUCCESS_DISTANCE: 1.0
    SENSORS: ["SEQUENTIAL_OBJECTGOAL_CATEGORY", "SEQUENTIAL_OBJECTGOAL_APPEARANCE"]
    SEQUENTIAL_OBJECTGOAL_APPERANCE:
        SEQUENTIAL_MODE: "MYOPIC"
        OUT_OF_CONTEXT: false
    GOAL_SENSOR_UUID: "objectgoal_appearance"
    MEASUREMENTS: ["DISTANCE_TO_NEXT_GOAL", "SEQUENTIAL_SUCCESS", "SEQUENTIAL_SPL"]

